create or replace PACKAGE C_VOLTALIA_UTIL_API AS

module_  CONSTANT VARCHAR2(25) := 'ENTERP';
lu_name_ CONSTANT VARCHAR2(25) := 'CVoltaliaUtil';
lu_type_ CONSTANT VARCHAR2(25) := 'Utility';

PROCEDURE Copy_Supplier (
    source_supplier_        varchar2,
    source_company_         varchar2,
    destination_            varchar2
);

PROCEDURE Copy_Iban (
    source_supplier_        varchar2,
    source_company_         varchar2,
    source_way_id_          varchar2,
    source_address_id_      varchar2,
    destination_            varchar2,
    disable_existing_       varchar2
);

    PROCEDURE Synchronize_User (
       user_     varchar2
    );

    PROCEDURE Synchronize_Company (
       company_     varchar2
    );

PROCEDURE Vlt_Close_Grp_Period ( 
company_in IN VARCHAR2, 
accounting_year_in IN INTEGER, 
accounting_period_in IN INTEGER, --if zero then it must close all the year periods
user_group_AC_in IN VARCHAR2, 
user_group_AP_in IN VARCHAR2, 
user_group_AR_in IN VARCHAR2, 
user_group_EX_in IN VARCHAR2, 
user_group_TR_in IN VARCHAR2
);

PROCEDURE Vlt_Close_Period ( 
company_in IN VARCHAR2, 
accounting_year_in IN INTEGER,
accounting_period_in IN INTEGER --if zero then it must close all the year periods
);

PROCEDURE VltCloseAccountPeriods(
inObjkey_ IN VARCHAR2, 
inUserId VARCHAR2
);

--Extract permissions
FUNCTION Vlt_CheckDupSupplierName(inSupplierName IN VARCHAR2) RETURN VARCHAR2;
FUNCTION Vlt_CheckDupSupplierAddress(inSupplierAddress IN VARCHAR2)  RETURN VARCHAR2;
FUNCTION Vlt_CheckDupSupplierVAT(inVATFreeVATCode IN VARCHAR2)  RETURN VARCHAR2;
FUNCTION Vlt_CheckDupSupplierAssNo(inAssociation_no IN VARCHAR2)  RETURN VARCHAR2 ;

--LOGS
--CREATE TABLE vlt_ifs_log (log_id      NUMBER        GENERATED BY DEFAULT ON NULL AS IDENTITY, loguser VARCHAR2(128) DEFAULT USER, ts TIMESTAMP DEFAULT SYSDATE, msg VARCHAR2(4000));
--CREATE TABLE vlt_ifs_log_status (logObject VARCHAR2(30), isActivated VARCHAR2(5) default 'FALSE');
PROCEDURE vlt_ifs_log_enable(inObject VARCHAR2);
PROCEDURE vlt_ifs_log_disable(inObject VARCHAR2);
FUNCTION Vlt_Check_ifs_log_for_object(inObject VARCHAR2) RETURN VARCHAR2;
PROCEDURE vlt_log_ifs (msg IN VARCHAR2, inObject VARCHAR2, startClean INTEGER);

--Approval rule tool
FUNCTION vlt_GetModelByObjkey(inObjkey VARCHAR2) RETURN VARCHAR2;
FUNCTION vlt_GetRuleID(inTemplateID VARCHAR2) RETURN VARCHAR2;
FUNCTION vlt_GetModelMin(inModelID VARCHAR2, inLevel NUMBER) RETURN NUMBER;
FUNCTION vlt_GetModelMax(inModelID VARCHAR2, inLevel NUMBER) RETURN NUMBER;
FUNCTION vlt_GetSite(inCompany VARCHAR2) RETURN VARCHAR2;
FUNCTION vlt_GetPriority(inProject_Category VARCHAR2) RETURN NUMBER;
FUNCTION vlt_CheckExistingPOAuthRule(inCompany VARCHAR2, inMinAmount NUMBER,inMaxAmount NUMBER,inTemplate_ID VARCHAR2, inSite VARCHAR2) RETURN VARCHAR2;
PROCEDURE vlt_CreatePOAuthRuleCat1Tab(inApprovalRule VARCHAR2, inCompany VARCHAR2, inCategory_DB VARCHAR2);
PROCEDURE vlt_CreatePOAuthRuleProjTab(inApprovalRule VARCHAR2, inCompany VARCHAR2, inProject_DB VARCHAR2);
PROCEDURE vlt_CreatePOAuthRule(inROWKEY VARCHAR2,inCompany VARCHAR2,inApproval_Rule VARCHAR2, inMinAmount NUMBER,inMaxAmount NUMBER,inTemplate_ID VARCHAR2, inSite VARCHAR2, inProject_Category_db VARCHAR2, inProject_db VARCHAR2) ;
PROCEDURE vlt_CreatePOAuthRuleGeneralTab(inROWKEY VARCHAR2);
FUNCTION vlt_GetTemplateID(inCompany VARCHAR2) RETURN VARCHAR2;
FUNCTION vlt_GetCompanyByObjkey(inObjkey VARCHAR2) RETURN VARCHAR2;
FUNCTION vlt_GetPersonByObjkey(inObjkey VARCHAR2) RETURN VARCHAR2;
FUNCTION vlt_GetApprovalTemplate(inCompany VARCHAR2, inUser1 VARCHAR2, inUser2 VARCHAR2) RETURN VARCHAR2;
PROCEDURE vlt_CreateApprovalTemplate(inLevel INTEGER, inCompany VARCHAR2, inUser1 VARCHAR2, inUser2 VARCHAR2);
PROCEDURE vlt_SetApprovalTemplate(inROWKEY VARCHAR2, inUserId IN VARCHAR2) ;
FUNCTION vlt_Get_Model_Num_Authorizers (inModel_ID VARCHAR2, inLevel NUMBER) RETURN NUMBER ;
FUNCTION vlt_Check_Model_BL (inModel_ID VARCHAR2, inBL_ID VARCHAR2) RETURN NUMBER;
FUNCTION vlt_Get_CategoryByObjkey (inObjkey VARCHAR2) RETURN VARCHAR2;
FUNCTION vlt_Get_ProjectCat1ByObjkey (inObjkey VARCHAR2) RETURN VARCHAR2;
FUNCTION vlt_Get_CategoryDescByCode (inCode VARCHAR2) RETURN VARCHAR2;
FUNCTION vlt_CheckProjectCompany (inProjectObjkey VARCHAR2, inCompanyObjkey VARCHAR2) RETURN NUMBER ;
FUNCTION vlt_GetLevel10(inCompany IN VARCHAR2, inUser1 IN VARCHAR2) RETURN VARCHAR2;
FUNCTION vlt_GetLevel20(inCompany IN VARCHAR2, inUser1 IN VARCHAR2, inUser2 IN VARCHAR2)  RETURN VARCHAR2;

--Supplier ID Creation
FUNCTION vlt_Get_Start_Supplier_ID(inCountry VARCHAR2) RETURN NUMBER;
PROCEDURE vlt_Get_New_Supplier_ID;

END C_VOLTALIA_UTIL_API;